### ISSUE TITLE
Sometimes this exception is still received on updates

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.registry.editor#19]
<pre>
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: javafx.scene.control.TreeItem cannot be cast to org.openbase.bco.registry.editor.struct.NodeContainer
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:219)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:224)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.getNodeByMessage(RegistryTreeTableView.java:230)
	at org.openbase.bco.registry.editor.visual.RegistryTreeTableView.update(RegistryTreeTableView.java:170)
	at org.openbase.bco.registry.editor.RegistryEditor.updateTreeTableView(RegistryEditor.java:564)
	at org.openbase.bco.registry.editor.RegistryEditor.access$900(RegistryEditor.java:105)
	at org.openbase.bco.registry.editor.RegistryEditor$5.run(RegistryEditor.java:452)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by pLeminoq** [comment]
This class cast exception is handled in after commit a10bba273d3cc005ed837e70ff4ab0d3ab0be1e3.
